os:
- linux
language: node_js
node_js: '12'
sudo: required
notifications:
  email:
  - minthilith@gmail.com
script:
- npm test
- npm run eslint
- npm run coverage
- bash <(curl -Ls https://coverage.codacy.com/get.sh) report --language javascript --coverage-reports coverage/lcov.info